#!/usr/bin/env python3
"""Build Mint Cleaner as a single executable file.

Mint Cleaner is Linux only (pkexec, apt, Linux paths), so there is one target:

    ./build-exe.py      -> dist/mint-cleaner-linux-<arch>-<version>-build<build>

Run it on the oldest system the file is meant for: it runs on every Linux with
the same or a newer glibc, never on an older one.

What it does:

1. creates a private build environment in ``build/exe/venv`` without the system
   packages, so nothing the build machine happens to have ends up in the file,
2. installs PyInstaller - Mint Cleaner itself needs nothing beyond the standard
   library and tkinter,
3. writes the VERSION file from the commit history (what ``version.py --write``
   does) and stages it with the icon as data,
4. runs PyInstaller and checks that the result starts.

Options:

    --clean     rebuild the build environment from scratch
    --keep-env  reuse the build environment without updating its packages
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import venv
from pathlib import Path
from typing import List

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

import paths  # noqa: E402
import version  # noqa: E402

BUILD_DIR = ROOT / "build" / "exe"
VENV_DIR = BUILD_DIR / "venv"
STAGE_DIR = BUILD_DIR / "stage"
WORK_DIR = BUILD_DIR / "work"
SPEC_FILE = WORK_DIR / "mint-cleaner.spec"
DIST_DIR = ROOT / "dist"

PYINSTALLER_SPEC = "pyinstaller>=6.9"

#: Read-only files the program opens at run time, relative to the project root.
#: The PNG window icons are not among them: they are rendered on first start.
DATA_FILES = ("resources/mint-cleaner.svg",)

#: Packages whose modules are all carried, whether or not PyInstaller sees them
#: imported. Everything else is found by following the imports of run.py.
SUBMODULE_PACKAGES = ["ui", "services"]

#: Top-level modules imported only inside functions.
HIDDEN_IMPORTS = ["bootstrap_ui", "paths", "version"]

SPEC_TEMPLATE = '''# Generated by build-exe.py - edit that script, not this file.
from PyInstaller.utils.hooks import collect_submodules

datas = {datas!r}
hiddenimports = {hidden!r}
for package in {submodules!r}:
    hiddenimports += collect_submodules(package)

a = Analysis(
    [{entry!r}],
    pathex=[{root!r}],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name={name!r},
    debug=False,
    strip=False,
    upx=False,
    runtime_tmpdir=None,
    console=False,
    icon=None,
)
'''


def info(message: str) -> None:
    """Print a progress line."""
    print("[build-exe] " + message, flush=True)


def fail(message: str) -> None:
    """Print an error and stop with exit code 1."""
    print("[build-exe] ERROR: " + message, file=sys.stderr, flush=True)
    sys.exit(1)


def venv_python() -> Path:
    """Return the interpreter of the build environment."""
    return VENV_DIR / "bin" / "python"


def run(command: List[object], **kwargs) -> None:
    """Run a command and stop the build when it fails."""
    info("$ " + " ".join(str(part) for part in command))
    completed = subprocess.run([str(part) for part in command], **kwargs)
    if completed.returncode != 0:
        fail("command failed with exit code {0}".format(completed.returncode))


def check_build_host() -> None:
    """Stop early when this machine cannot produce a working program."""
    if not sys.platform.startswith("linux"):
        fail("Mint Cleaner is Linux only (pkexec, apt); build it on Linux.")
    try:
        import tkinter  # noqa: F401
    except ImportError:
        fail("tkinter is missing - sudo apt install python3-tk")


def bundled_packages() -> List[str]:
    """Return the pip packages to install into the build environment."""
    return [PYINSTALLER_SPEC]


def prepare_venv(clean: bool, keep: bool) -> None:
    """Create or refresh the build environment.

    It is created without the system packages; tkinter comes with the base
    interpreter's standard library, which the environment shares.
    """
    if clean and VENV_DIR.exists():
        info("Removing the old build environment ...")
        shutil.rmtree(str(VENV_DIR))
    if not venv_python().exists():
        info("Creating the build environment in {0} ...".format(VENV_DIR))
        venv.EnvBuilder(with_pip=True).create(str(VENV_DIR))
    elif keep:
        info("Reusing the build environment as it is.")
        return
    run([venv_python(), "-m", "pip", "install", "--upgrade", "--disable-pip-version-check", "pip"])
    run([venv_python(), "-m", "pip", "install", "--upgrade", "--disable-pip-version-check"]
        + bundled_packages())


def write_version() -> version.Version:
    """Write the VERSION file from the history and return what it says.

    The executable reads only this file: it has no history to derive from.
    """
    found = version.write_file() or version.from_file(ROOT)
    if found is None or not found.is_known:
        fail("no version: neither a git history nor a VERSION file (clone with full history).")
    version.forget()
    return found


def stage_data(found: version.Version) -> Path:
    """Copy the read-only files the executable carries, in the checkout's layout.

    :param found: The version to carry as the VERSION file.
    :return: The staged root, unpacked as ``sys._MEIPASS`` at run time.
    """
    if STAGE_DIR.exists():
        shutil.rmtree(str(STAGE_DIR))
    for relative in DATA_FILES:
        source = ROOT / relative
        if not source.is_file():
            fail("{0} is missing".format(source))
        destination = STAGE_DIR / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(str(source), str(destination))
    (STAGE_DIR / version.VERSION_FILE.name).write_text(found.line() + "\n", encoding="utf-8")
    info("Staged {0} data files and VERSION {1}.".format(len(DATA_FILES), found.label))
    return STAGE_DIR


def spec_text(staged: Path) -> str:
    """Return the PyInstaller spec file.

    :param staged: The staged root from :func:`stage_data`.
    :return: The content of the spec file.
    """
    return SPEC_TEMPLATE.format(
        datas=[(str(staged), ".")],
        hidden=HIDDEN_IMPORTS,
        submodules=SUBMODULE_PACKAGES,
        entry=str(ROOT / "run.py"),
        root=str(ROOT),
        name=paths.executable_name(),
    )


def smoke_test(executable: Path, found: version.Version) -> None:
    """Start the result once and make sure it answers with its version."""
    info("Starting {0} --version ...".format(executable.name))
    completed = subprocess.run([str(executable), "--version"], stdout=subprocess.PIPE,
                               stderr=subprocess.STDOUT, timeout=300)
    output = completed.stdout.decode("utf-8", errors="replace").strip()
    if completed.returncode != 0:
        fail("the executable did not start (exit code {0}):\n{1}".format(completed.returncode, output))
    # The full label carries a "·", which a non-UTF-8 terminal replaces.
    expected = "{0} ({1})".format(found.name, found.build)
    if output and expected not in output:
        fail("the executable reports {0!r}, expected {1}".format(output, expected))
    info("OK: " + (output or "exit code 0"))


def main() -> int:
    """Run the whole build."""
    parser = argparse.ArgumentParser(description="Build Mint Cleaner as a single executable file (Linux only).")
    parser.add_argument("--clean", action="store_true", help="rebuild the build environment from scratch")
    parser.add_argument("--keep-env", action="store_true",
                        help="reuse the build environment without updating its packages")
    args = parser.parse_args()

    check_build_host()
    found = write_version()
    info("Mint Cleaner {0} as {1}".format(found.label, paths.executable_name()))
    prepare_venv(clean=args.clean, keep=args.keep_env)
    staged = stage_data(found)
    WORK_DIR.mkdir(parents=True, exist_ok=True)
    SPEC_FILE.write_text(spec_text(staged), encoding="utf-8")
    run([venv_python(), "-m", "PyInstaller", "--noconfirm", "--clean",
         "--distpath", DIST_DIR, "--workpath", WORK_DIR, SPEC_FILE], cwd=str(ROOT))

    result = DIST_DIR / paths.executable_name()
    if not result.is_file():
        fail("PyInstaller finished but {0} is missing".format(result))
    smoke_test(result, found)
    info("Done: {0} ({1:.1f} MB)".format(result, result.stat().st_size / 1048576))
    return 0


if __name__ == "__main__":
    sys.exit(main())
